### ISSUE TITLE
thanks for sharing the code! I wonder if you can upload warmup_scheduler.py? thanks!

### ISSUE THREAD

**Issue by wjxts** [omihub777/ViT-CIFAR#1]

**Comment by wjxts** [comment]
and AutoAugment?

**Comment by omihub777** [comment]
Hi, @wjxts !👋
Did you run setup.sh as README says?

It installs all required packages such as warmup and AutoAugment.
I don’t plan to upload those files bc you can download all of them by just running setup.sh.
