### ISSUE TITLE
About FID score

### ISSUE THREAD

**Issue by konglk1203** [omihub777/ViT-CIFAR#4]
Hi, thank you for kindly sharing the code. I am trying to reproduce the result. Everything goes smoothly. The max SWD matches fig 8 and new image generated seems make sence. However, I don't know why the FID score seems not working. At the beginning it is about 300. After about 200 epochs, it becomes 130 and stuck for at least the next 200 epochs. So I just stop continuing running it. Could you tell me why it is not work? What I did is run SIG on MNIST.

**Comment by omihub777** [comment]
Hi, @konglk1203 !
Thank you for your interest in my work. What do you mean by fig 8?
In this work, I don't generate any images so I am not sure why you mention FID score and others.
A little bit more clarification would be helpful to discuss your issue.

**Comment by konglk1203** [comment]
[output.txt](https://github.com/omihub777/ViT-CIFAR/files/8075989/output.txt)
Sorry for didn't make myself clear. This is the output of what I get from SIG on MNIST. I think the program runs pretty good since the Wasserstein Distance decreases as expected as shown in fig 8 in the paper. However, I cannot understand why FID score (around 130) is so different from what is shown in table 4 in the paper, which is 4.5.
Thank you!

**Comment by konglk1203** [comment]
I am so sorry, I am working on ViT and SINF together and I left the comment under the wrong project... So sorry for bothering you. Could you help me remove the issue? I guess this would not be helpful for others
