### ISSUE TITLE
AttributeError: Can't pickle local object 'SubPolicy.__init__.<locals>.<lambda>'

### ISSUE THREAD

**Issue by SJTUzhou** [omihub777/ViT-CIFAR#7]
Same issue, please see https://github.com/DeepVoltaire/AutoAugment/issues/16.
Solution found at https://github.com/DeepVoltaire/AutoAugment/pull/30/commits
Please update autoaugment.py and ops.py

**Comment by omihub777** [comment]
@SJTUzhou 
I'm sorry for not getting back to you sooner. I applied a fix patch according to your reference just now. Thank you!
